<h3>1: Lists</h3>
<b>1) Make a list with the spelled-out number strings ‘one’, ‘two’,
‘three’, ‘four’, and ‘five’ in that order and call it myList.</b>

In [14]:
myList = ["one", "two", "three", "four", "five"]
myList

['one', 'two', 'three', 'four', 'five']

<b>2) Remove ‘three’ from the list using positional indexing</b>

In [15]:
myList.pop(2)
myList

['one', 'two', 'four', 'five']

<b>3) Check if ‘four’ is in the list.</b>

In [16]:
if "four" in myList:
    print("Exist")
else:
    print("Doesn't Exist")

Exist


<b>4) Append ‘six’ to the end of the list, then print the length of the
list.</b>

In [17]:
myList.append("six")
print(myList)
print(f"length of myList is {len(myList)}")

['one', 'two', 'four', 'five', 'six']
length of myList is 5


<b>5) Print the contents of the list, but also next to each item print
the length of the string (e.g. one is 3, four is 4) using a for loop.</b>

In [18]:
for i in myList:
    print(f"{i} is {len(i)}")

one is 3
two is 3
four is 4
five is 4
six is 3


<b>6) Create a list only of the lengths of the strings and show your
result. You can use the loop before to fill the list.</b>

In [19]:
myList_length = [len(i) for i in  myList]
print(myList_length)

[3, 3, 4, 4, 3]


<h3>2: Dictionaries</h3>

<b>1) Make a dictionary with the keys be English words as below, and the
values be the translation. You can use this language example (German)
or choose your own. Note: you need to make sure all of these words
are represented as strings, in quotes.</b>
<br>
<b>apple - Apfel
apples - Äpfel
I - Ich
and - und
like - mag
strawberries - Erdbeeren</b>

In [22]:
translate_dict = {"apple":"Apfel", "apples":"Äpfel", "I":"Ich", "and":"und", "like":"mag", "strawberries":"Erdbeeren"}
translate_dict

{'apple': 'Apfel',
 'apples': 'Äpfel',
 'I': 'Ich',
 'and': 'und',
 'like': 'mag',
 'strawberries': 'Erdbeeren'}

<b>2) Use the dictionary to look up the translation for ‘apple’ and
‘like’.</b>

In [33]:
if "apple" in translate_dict:
    print(translate_dict["apple"])
if "like" in translate_dict:
    print(translate_dict["like"])

Apfel
mag


<b>3) Make a variable var with the string “I like apples and
strawberries”.</b>

In [43]:
var = "I like apples and strawberries"
var

'I like apples and strawberries'

<b>4) Now create a list from var with each word a separate item (this is
a string split operation).</b>

In [44]:
var_list = var.split(" ")
var_list

['I', 'like', 'apples', 'and', 'strawberries']

<b>5) Iterate through the list you’ve created and replace any word in
your dictionary with the translation.</b>

In [45]:
for i in range(len(var_list)):
    var_list[i] = translate_dict[var_list[i]]
print(var_list)

['Ich', 'mag', 'Äpfel', 'und', 'Erdbeeren']


<b>6) Now take your new list and turn it into a string with spaces
between the words.</b>

In [46]:
print(" ".join(var_list))

Ich mag Äpfel und Erdbeeren


<h3>3: Arrays</h3>

<b>1) Create an array of zeros of size 8 x 8 and print the data type of
the array.</b>

In [48]:
import numpy as np

In [53]:
zero_array = np.zeros((8, 8), dtype="int64")
print(zero_array)
print(f"\n\ndata type of zero_array is {type(zero_array)}")

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


data type of zero_array is <class 'numpy.ndarray'>


<b>2) Fill the array with the numbers 1 to 64 first by row, then by
column. You may want to use a for loop inside a for loop to do this.</b>

In [55]:
counter = 1
for i in range(8):
    for j in range(8):
        zero_array[i][j] = counter
        counter+=1
print(zero_array)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


<b>3) Transpose the array.</b>

In [57]:
print(np.transpose(zero_array))

[[ 1  9 17 25 33 41 49 57]
 [ 2 10 18 26 34 42 50 58]
 [ 3 11 19 27 35 43 51 59]
 [ 4 12 20 28 36 44 52 60]
 [ 5 13 21 29 37 45 53 61]
 [ 6 14 22 30 38 46 54 62]
 [ 7 15 23 31 39 47 55 63]
 [ 8 16 24 32 40 48 56 64]]


<b>4) Print only the top 4 rows and columns.</b>

In [63]:
print(zero_array[:4, :4])

[[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]
 [25 26 27 28]]


<b>5) Make a 1D array out of your 2D array with the numbers 1 to 64 in
order (note the column vs row issue, you may need transposes.)</b>

In [68]:
reshape_array = zero_array.reshape((64))
print(reshape_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]


<b>6) Now take that 1D array you made from before and reshape it back to
the original 2D array.</b>

In [69]:
print(reshape_array.reshape(8, 8))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


<h3>Part 2: Applications</h3>
<h3>1. Word Counts</h3>

<b>Word counts are often used in text processing to automatically classify documents by
topic. They are also used to automatically measure the “sentiment” by counting, for
example, the number of positive or negative words used in the comment or essay. Write
code to count the number of unique words in a very large string using the following
steps.
a) First convert the string to a list with each word a separate item in the list. Hint:
use a string split function for your language, and make sure it separates by “ ”.
b) Then use a dictionary to associate each word with a count. Note, the dictionary
won’t be able to increment a key unless you add it first, so you may have to
check to see if it exists before setting the original count of a word to 1.
c) Print each word and its count afterwards, and test with an interesting block of text
that will have multiple words counted multiple times. (Note, the words don’t have
to be in any particular order.)
For example: “how much wood would a woodchuck chuck if a woodchuck could chuck
wood”
Expected output:
how - 1
much -1
wood - 2
would - 1
a - 2
woodchuck - 2
chuck - 2
if - 1
could - 1
</b>

In [72]:
var = "how much wood would a woodchuck chuck if a woodchuck could chuck wood"
print(var)

how much wood would a woodchuck chuck if a woodchuck could chuck wood


In [73]:
words = var.split(" ")
print(words)

['how', 'much', 'wood', 'would', 'a', 'woodchuck', 'chuck', 'if', 'a', 'woodchuck', 'could', 'chuck', 'wood']


In [77]:
words_freq = {}
for word in words:
    if word in words_freq:
        words_freq[word]+=1
        continue
    words_freq[word] = 1
print(words_freq)

{'how': 1, 'much': 1, 'wood': 2, 'would': 1, 'a': 2, 'woodchuck': 2, 'chuck': 2, 'if': 1, 'could': 1}


In [78]:
for word, freq in words_freq.items():
    print(f"{word} - {freq}")

how - 1
much - 1
wood - 2
would - 1
a - 2
woodchuck - 2
chuck - 2
if - 1
could - 1


<h3>2. Adding an Array Border</h3>

<b>As we will see later in the class, arrays can be used to represent images. In particular,
black and white images can be represented by a 2D array, with one number (usually 0)
representing black and another number (usually 1, but sometimes something else)
representing white, and gray being everything in between. Here we just want to test
your ability to handle a 2D array and add a border (filled with 0's) around it. In code this
means creating an array of 0’s of width+2 by height+2 size and copying the original
array into the middle appropriately (Note: do not use np.pad() function).
Test with an array in the center that has non-zero elements. First print the original array,
then print the new array with the added border of 0’s.</b>

In [90]:
row_size = 3
col_size = 4
ones_array = np.ones((row_size, col_size), dtype="int64")
# print(ones_array)
zeros_array = np.zeros((row_size+2, col_size+2), dtype="int64")
# print(zeros_array)
zeros_array[1:row_size+1, 1:col_size+1] = ones_array
print(f"Original Array \n{ones_array}")
print("\n")
print(f"New Array \n {zeros_array}")

Original Array 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


New Array 
 [[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


<h3>3. Functions</h3>

<b>Encapsulate the previous code into functions. The first function word_count(text)
prints each word and its count of text. The second function add_border(array)
prints the original array and the new array with the added border of 0’s.</b>

In [96]:
def word_count(text):
    words = var.split(" ")
#     print(words)
    words_freq = {}
    for word in words:
        if word in words_freq:
            words_freq[word]+=1
            continue
        words_freq[word] = 1
#     print(words_freq)
    for word, freq in words_freq.items():
        print(f"{word} - {freq}") 

In [104]:
def add_border(array):
    row_size = array.shape[0]
    col_size = array.shape[1]
    ones_array = np.ones((row_size, col_size), dtype="int64")
    # print(ones_array)
    zeros_array = np.zeros((row_size+2, col_size+2), dtype="int64")
    # print(zeros_array)
    zeros_array[1:row_size+1, 1:col_size+1] = ones_array
    print(f"Original Array \n{ones_array}")
    print("\n")
    print(f"New Array \n {zeros_array}")

In [97]:
var = "how much wood would a woodchuck chuck if a woodchuck could chuck wood"
word_count(var)

how - 1
much - 1
wood - 2
would - 1
a - 2
woodchuck - 2
chuck - 2
if - 1
could - 1


In [105]:
add_border(np.ones((5, 6), dtype="int64"))

Original Array 
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


New Array 
 [[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]
